### PR TITLE
Improve reconnection handling

### PR DESCRIPTION
**Pull request by philipparndt**
fixes https://github.com/philipparndt/miele-to-mqtt-gw/issues/40

@AleksCee can you try this with your configuration?

### CODE REVIEW

**Comment by AleksCee** [comment]
Hi,
The build failed:
[ERROR] /opt/miele-to-mqtt-gw/de.rnd7.mieletomqtt/src/main/java/de/rnd7/mieletomqtt/MielePollingHandler.java:39:23: Parameter seconds should be final. [FinalParameters]
Audit done.

**Comment by AleksCee** [comment]
After fixing the error local it’s seams to work:

18:25:08.446 INFO  - Info enabled
18:25:08.585 INFO  - Connecting MQTT client
18:25:09.077 INFO  - MQTT client connected
18:25:11.602 INFO  - Using Miele SSE api

**Comment by AleksCee** [comment]
How long should I test it? I hope in the next time there is no internet break like the last week... ;)

**Comment by philipparndt** [comment]
Sorry, I should have waited for the CI to finish ;)

I tested it by disable the network adapter. So reconnection should work in production as well.
The app tries to reconnect 10 times and it waited between each try for two minutes. Maybe we should make this configurable. After this time, the application shuts down and a new container can be started (based on the docker restart policy)

**Comment by AleksCee** [comment]
Ok, the container is on my NAS and this is a Custer, if I hard stop the interface the cluster will turn over. I seams it’s a little bit to hard for a test in me case. Perhaps I can test to block the domain via pihole. :-)

**Pull request merged**
