### PR TITLE
Exclude signatures from external dependencies

### PR DESCRIPTION
**Pull request by AleksCee**
Fix java.lang.SecurityException on jar starting. Hopes to fix the issue #25

### CODE REVIEW

**Comment by philipparndt** [comment]
Thanks, yes this should fix it. The maven shade plugin will copy all files from the external dependencies to the final jar. Which results in an invalid signature.

**Comment by AleksCee** [comment]
@philipparndt sorry this was my first pull-request - how can I now sync my fork with yours or have I delete this and fork it again for a future pull-request?
Thanks, Alex

**Comment by philipparndt** [comment]
@AleksCee 

Have a look at the description here:
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

You have to set the upstream first and then pull from this. Give it a try, you can do nothing wrong ;)

I always suggest always creating a branch when doing changes on a fork. Otherwise, you need to request the changes from your master and are locked out for future changes until your PR is merged.

**Comment by AleksCee** [comment]
@philipparndt ok, I have just fork via Browser and update the file online. So my fork now shows: ' This branch is 1 commit ahead, 1 commit behind philipparndt:master. ' - is the best way to delete it?
above this line github says 

> 
> Pull request closed
> 
> If you wish, you can delete this fork of philipparndt/miele-to-mqtt-gw in the settings.

So, should I delete it?

**Comment by philipparndt** [comment]
you can delete it and create it again for the next change, or update it using a git cli.

**Pull request merged**
