### PR TITLE
Java 15, logback, dependency update

### PR DESCRIPTION
**Pull request by philipparndt**
Hi @AleksCee

can you test this PR?

- added default logback.xml at log level info
- added hint on logger in README.md
- Java 15
- Optimized docker image (multi stage build) - no sources + maven in production image

### CODE REVIEW

**Comment by AleksCee** [comment]
I‘m not to familiar with git, how did I do this in a easy was?

**Comment by philipparndt** [comment]
You can execute the following:

```
git clone https://github.com/philipparndt/miele-to-mqtt-gw.git
git checkout java15
```

and then build the docker container.

**Comment by philipparndt** [comment]
hmm, there is no java15 build for raspi :( I think I need to downgrade the java version.

**Comment by AleksCee** [comment]
Build runs but the logs are still there:
14:47:31.424 [pool-1-thread-2] DEBUG de.rnd7.mieletomqtt.mqtt.GwMqttClient -

**Pull request merged**
