### PR TITLE
Add integration tests

### PR DESCRIPTION
**Pull request by philipparndt**
Implement integration tests using testcontainers

### CODE REVIEW

**Comment by philipparndt** [comment]
@AleksCee can you please run the test cases with your configuration?
They should be fine, but just in case of a case.

**Comment by AleksCee** [comment]
Hi @philipparndt 

the build was fine. First Test block was ok but second seams do nothing?

```

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running de.rnd7.miele.api.MieleAPITest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.683 s - in de.rnd7.miele.api.MieleAPITest
[INFO] Running de.rnd7.miele.api.MieleDeviceTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in de.rnd7.miele.api.MieleDeviceTest
[INFO] Running de.rnd7.miele.api.SSEClientTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 21.936 s - in de.rnd7.miele.api.SSEClientTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
```

```
[INFO] Compiling 5 source files to /opt/miele-to-mqtt-gw/de.rnd7.mieletomqtt/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ de.rnd7.mieletomqtt ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
```

now I will try to start the Docker... just a moment, I musst Trick a Little Bit with Synology-Docker .... :-)

**Comment by AleksCee** [comment]
Ok, the Docker Runs and I get Updates from the running device an only a init message from the off device.
Seams ok, but reconnect  can’t test right now, must wait for some time an watch the logs.

**Comment by AleksCee** [comment]
Oh I see you have add the reconnect Test in the build process... ok, seams to work.

**Comment by philipparndt** [comment]
changes merged in https://github.com/philipparndt/miele-to-mqtt-gw/pull/30

**Pull request closed without merging**
